Repository SejongOSS/triangle, pull requests merged in 2025-05, with the labels that each got.

#11 Feat: Button component 구현
  triangle/package-lock.json
  triangle/package.json
  triangle/src/App.js
  triangle/src/components/Button.css
  triangle/src/components/Button.jsx
  triangle/src/components/dump
Labels: ⭐️ feature, 🍀 FE

#23 [Docs] Create pull_request_template.md
  .github/pull_request_template.md
Labels: 📑 docs

#24 [FE/FEATURE] 라우터 구현
  triangle/src/App.js
  triangle/src/layouts/UserLayout.css
  triangle/src/layouts/UserLayout.jsx
  triangle/src/pages/NotFoundPage.jsx
  triangle/src/pages/TestPage.jsx
  triangle/src/router.jsx
Labels: ⭐️ feature, 🍀 FE

#7 Feat : 로고 포함한 헤더 구현
  package-lock.json
  triangle/src/assets/images/triangle_logo.png
  triangle/src/components/TopNavbar.css
  triangle/src/components/TopNavbar.js
Labels: ⭐️ feature, 🍀 FE

#9 Feat : 동아리 개별 페이지 정보 박스 구현
  triangle/src/components/ClubinfoBox.css
  triangle/src/components/ClubinfoBox.js
Labels: ⭐️ feature, 🍀 FE

#15 Feat: 검색 컴포넌트 구현
  triangle/src/assets/images/search_icon.svg
  triangle/src/components/SearchBox.css
  triangle/src/components/SearchBox.js
Labels: ⭐️ feature, 🍀 FE

#19 Feat: 동아리 검색 결과 컴포넌트 구현
  triangle/package-lock.json
  triangle/src/assets/images/filled_star.svg
  triangle/src/assets/images/star.svg
  triangle/src/components/ClubNameBox.css
  triangle/src/components/ClubNameBox.jsx
Labels: ⭐️ feature, 🍀 FE

#25 Feat: Dialog 컴포넌트 구현
  triangle/src/components/Dialog.css
  triangle/src/components/Dialog.jsx
Labels: ⭐️ feature, 🍀 FE

#29 Feat : 상세페이지 동아리프로필 컴포넌트 구현
  triangle/src/assets/images/sejong_logo.png
  triangle/src/components/clubDetailTitle/clubDetailTitle.css
  triangle/src/components/clubDetailTitle/clubDetailTitle.js
Labels: ⭐️ feature, 🍀 FE

#14 Feat: 랜딩 페이지 구현
  triangle/package-lock.json
  triangle/src/components/Dialog.css
  triangle/src/components/Dialog.jsx
  triangle/src/pages/LandingPage.css
  triangle/src/pages/LandingPage.jsx
  triangle/src/pages/dump
Labels: ⭐️ feature, 🍀 FE

#32 [FEATURE] 챗봇 렌딩페이지 구현
  triangle/src/assets/images/chatbot_image.png
  triangle/src/components/ChatBot/ChatBot.jsx
  triangle/src/components/FeatureCard/FeatureCard.css
  triangle/src/components/FeatureCard/FeatureCard.jsx
  triangle/src/components/SectionTitle/SectionTitle.css
  triangle/src/components/SectionTitle/SectionTitle.jsx
  triangle/src/components/TestimonialCard/TestimonialCard.css
  triangle/src/components/TestimonialCard/TestimonialCard.jsx
  triangle/src/pages/DescriptionChatBotPage/DescriptionChatBotPage.css
  triangle/src/pages/DescriptionChatBotPage/DescriptionChatBotPage.jsx
Labels: ⭐️ feature, 🍀 FE

#33 Feat: 동아리수 표시, 정렬 컴포넌트 구현
  triangle/package-lock.json
  triangle/src/components/ClubSort/ClubCountAndAlignBox.css
  triangle/src/components/ClubSort/ClubCountAndAlignBox.jsx
  triangle/src/components/ClubSort/SortDropDown.css
  triangle/src/components/ClubSort/SortDropDown.jsx
  triangle/src/pages/TestPage.jsx
Labels: ⭐️ feature, 🍀 FE

#35 [REFACTOR] css naming 변경 및 Component Packaging 변경
  triangle/src/components/Button/Button.css
  triangle/src/components/Button/Button.jsx
  triangle/src/components/Dialog/Dialog.css
  triangle/src/components/Dialog/Dialog.jsx
  triangle/src/pages/LandingPage/LandingPage.css
  triangle/src/pages/LandingPage/LandingPage.jsx
  triangle/src/router.jsx
Labels: ⚒️ refactor, 🍀 FE

#37 Refactor: About button에 Dialog Component 추가
  triangle/src/pages/LandingPage/LandingPage.jsx
Labels: ⚒️ refactor, 🍀 FE

#51 [Feature] 페이지 이동 기능 구현
  triangle/src/pages/DescriptionChatBotPage/DescriptionChatBotPage.jsx
  triangle/src/pages/LandingPage/LandingPage.jsx
  triangle/src/pages/MainPage/MainPage.jsx
  triangle/src/router.jsx
Labels: ⭐️ feature, 🍀 FE

#53 Update README.md
  README.md
Labels: 📤 release

#56 Fix: LandingPage of Router 비활성화
  triangle/src/router.jsx
Labels: ❗️bug, 🍀 FE, 📤 release

#59 HotFix: 버튼 이벤트 발생 시 세부 페이지 출력되게 수정
  triangle/src/pages/MainPage/MainPage.jsx
Labels: ❗️bug, 🍀 FE

#63 [Feature] 즐겨찾기 기능 구현
  triangle/src/components/ClubNameBox.jsx
Labels: ⭐️ feature, 🍀 FE

#61 [Refactor] 헤더 수정
  triangle/src/components/TopNavbar.css
  triangle/src/components/TopNavbar.jsx
  triangle/src/router.jsx
Labels: ⚒️ refactor, 🍀 FE

#66 [REFACTOR] 기존 랜딩페이지 디자인 수정
  triangle/src/assets/images/github-mark.svg
  triangle/src/components/Dialog/Dialog.css
  triangle/src/components/Dialog/Dialog.jsx
  triangle/src/components/FavoriteSection/FavoriteSection.css
  triangle/src/components/FavoriteSection/FavoriteSection.jsx
  triangle/src/pages/DescriptionChatBotPage/DescriptionChatBotPage.css
  triangle/src/pages/DescriptionChatBotPage/DescriptionChatBotPage.jsx
  triangle/src/pages/LandingPage/LandingPage.jsx
  triangle/src/router.jsx
Labels: ⭐️ feature, ⚒️ refactor

#72 Feat: openai prompt
  triangle/src/constants/dump
  triangle/src/constants/prompts.js
  triangle/src/services/openaiService.js
Labels: ⭐️ feature

#77 [Feature] 동아리 정보 json파일 수정. 상세정보 추가
  triangle/src/constants/sejong_all_clubs.json
Labels: ⭐️ feature, 📑 docs

#79 [REFACTOR] router 수정 및 레이아웃 최신화
  triangle/src/components/ChatBot/ChatBot.jsx
  triangle/src/components/Footer/Footer.css
  triangle/src/components/Footer/Footer.jsx
  triangle/src/components/TopNavbar.jsx
  triangle/src/layouts/DescriptionLayout/DescriptionLayout.jsx
  triangle/src/layouts/UserLayout/UserLayout.css
  triangle/src/layouts/UserLayout/UserLayout.jsx
  triangle/src/pages/DescriptionChatBotPage/DescriptionChatBotPage.css
  triangle/src/pages/DescriptionChatBotPage/DescriptionChatBotPage.jsx
  triangle/src/pages/MainPage/MainPage.jsx
  triangle/src/router.jsx
Labels: ⚒️ refactor, 🍀 FE

#82 [Feature] 그래프 페이지 구현
  triangle/package-lock.json
  triangle/src/assets/images/graph_icon.png
  triangle/src/components/ClubCountInfoBox/ClubCountInfoBox.css
  triangle/src/components/ClubCountInfoBox/ClubCountInfoBox.jsx
  triangle/src/components/PieGraph/PieGraph.jsx
  triangle/src/components/TopNavbar.css
  triangle/src/components/TopNavbar.jsx
  triangle/src/pages/GraphPage/GraphPage.css
  triangle/src/pages/GraphPage/GraphPage.jsx
  triangle/src/router.jsx
Labels: ⭐️ feature, 🍀 FE

#83 [Feature] 즐겨찾기 필터 기능 구현
  triangle/src/components/ClubCategoryBox.jsx
  triangle/src/components/ClubNameBox.jsx
  triangle/src/pages/MainPage/MainPage.jsx
Labels: ⭐️ feature, 🍀 FE

#86 Refactor: 패키지 분리 및 import문 수정
  triangle/src/components/ClubCategoryBox/ClubCategoryBox.css
  triangle/src/components/ClubCategoryBox/ClubCategoryBox.jsx
  triangle/src/components/ClubNameBox/ClubNameBox.css
  triangle/src/components/ClubNameBox/ClubNameBox.jsx
  triangle/src/components/SearchBox/SearchBox.css
  triangle/src/components/SearchBox/SearchBox.jsx
  triangle/src/components/TopNavbar/TopNavbar.css
  triangle/src/components/TopNavbar/TopNavbar.jsx
  triangle/src/layouts/UserLayout/UserLayout.jsx
  triangle/src/pages/MainPage/MainPage.jsx
  triangle/src/pages/NotFoundPage/NotFoundPage.jsx
  triangle/src/pages/TestPage/TestPage.jsx
  triangle/src/router.jsx
Labels: ⚒️ refactor, 🕹️chore
